<a href="https://colab.research.google.com/github/btg1631/study_AIs/blob/main/docs/MLs/Regression/01_linearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Regression (회귀) 예측

- 데이터
- 모델
- 평가

### 데이터 관련

In [14]:
from sklearn import datasets
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

In [15]:
# type(diabetes_X), type(diabetes_y)  # (numpy.ndarray, numpy.ndarray)
diabetes_X.shape, diabetes_y.shape

((442, 10), (442,))

### 모델

In [16]:
from sklearn import linear_model

In [17]:
linearRegresiion = linear_model.LinearRegression()  # 학습 장소 선택

In [18]:
linearRegresiion.fit(diabetes_X, diabetes_y)  # 학습 진행

LinearRegression()

### 평가

In [19]:
diabetes_X[:2], diabetes_y[:2]

(array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
         -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
         -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405]]),
 array([151.,  75.]))

In [20]:
linearRegresiion.predict(diabetes_X[:2])

array([206.11667725,  68.07103297])