In [1]:
import pandas as pd
import pyLDAvis
import pyLDAvis.lda_model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import fetch_20newsgroups
# 데이터 로드
data = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))
documents = data.data

In [2]:
documents[:1]

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.']

### TfidfVectorizer
max_df=, min_df=

In [3]:
tfidfVectorizer = TfidfVectorizer(stop_words='english', max_df=0.95, min_df=2)

In [4]:
tfidf = tfidfVectorizer.fit_transform(documents)
tfidf.toarray()[:1]

array([[0., 0., 0., ..., 0., 0., 0.]])

In [5]:
import numpy as np
np.where(tfidf.toarray()[:1] > 0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 2582,  2918,  4348,  7279,  7618,  7843,  8160,  8308, 11269,
        12709, 12710, 13133, 13725, 13755, 15821, 17670, 18895, 20611,
        20958, 21663, 21665, 22151, 23553, 27879, 29041, 29858, 30936,
        31406, 32237, 32669, 32807, 37946, 38743]))

In [6]:
latentDirichletAllocation3 = LatentDirichletAllocation(n_components=3, n_jobs=-1)

In [7]:
latentDirichletAllocation3.fit(tfidf)

LatentDirichletAllocation(n_components=3, n_jobs=-1)

In [9]:
vis = pyLDAvis.lda_model.prepare(latentDirichletAllocation3, tfidf, tfidfVectorizer)

In [10]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis)

In [11]:
latentDirichletAllocation5 = LatentDirichletAllocation(n_components=5, n_jobs=-1)

In [12]:
latentDirichletAllocation5.fit(tfidf)

LatentDirichletAllocation(n_components=5, n_jobs=-1)

In [13]:
vis = pyLDAvis.lda_model.prepare(latentDirichletAllocation5, tfidf, tfidfVectorizer)

In [14]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis)

In [15]:
latentDirichletAllocation7 = LatentDirichletAllocation(n_components=7, n_jobs=-1)

In [16]:
latentDirichletAllocation7.fit(tfidf)

LatentDirichletAllocation(n_components=7, n_jobs=-1)

In [17]:
vis = pyLDAvis.lda_model.prepare(latentDirichletAllocation7, tfidf, tfidfVectorizer)

In [18]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis)